[package]
name = "tiny"
version = "0.1.0"
edition = "2021"

[dependencies]
getopts = "0.2.21"
ndarray = "0.16.0"
rand = "0.8.5"
serde = { version = "1.0.204", features = ["serde_derive"] }
serde_json = "1.0.122"
zmq = "0.10.0"
